"""empty message

Revision ID: dee911561e43
Revises: 3053df054c7b
Create Date: 2023-12-26 19:02:08.368328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee911561e43'
down_revision = '3053df054c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_user_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contact_user_token_fkey', 'user', ['user_token'], ['id'])

    # ### end Alembic commands ###
